Algoritmo "contador_pulo2"

// Disciplina  : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : Aula 11 – Estruturas de Repetição 3
// Autor(a)    : Thaina Helena
// Ano         : 2020

Var

   // Variáveis
   contador: inteiro

Inicio

      // Contador com FOR por passo:
      Escreval("Olá! Sou um contador! Conto até 10!")
      Para contador <- 1 ate 10 passo 2 faca
             Escreval(contador)
      FimPara
      Escreval("Terminei de contar!")
      
Fimalgoritmo